apiVersion: v1
kind: Service
metadata:
  name: hello-secret-file-service
spec:
  selector:
    app: hello-secret-file
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
